repos:
-   repo: git://github.com/pre-commit/mirrors-yapf
    rev: v0.28.0
    hooks:
    - id: yapf
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]