repos:
-   repo: git@github.com:leaprovenzano/black.git
    rev: master
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]